name: "[APP-WEB] Build Test"
on:
  pull_request:
    branches:
      - development
    paths:
      - 'chatbots/team/botify-team-bot/**'
  workflow_call:
    secrets: inherit
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  JOVO_STAGE: staging
  JOVO_LOG_LEVEL: WARN
  AIRTABLE_BASE_ID_TURNS: 1234
  AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_APIKEY }}
  RASA_NLU: http://rasa.nlu/
  SIPGATE_API_URI: http://localhost:6000
  ROUTER_URI: http://sipgate.router/
  STATUSPAGE_URI: http://sipgate.statuspage/

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: chatbots/team/botify-team-bot

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@sipgate'
      - run: npm install
      - run: npm run prettier
      - run: npm run eslint
      - run: npm run build
      - run: npm run test
